package trafficsync.common;

public enum MessageType {
    REGISTER,
    REGISTER_ACK,
    TOPOLOGY,
    TRAFFIC_UPDATE,
    ACCIDENT_ALERT,
    SIGNAL_CHANGE,
    MARKER,
    SNAPSHOT_REQUEST,
    SNAPSHOT_RESPONSE,
    PING,
    STATUS_REQUEST,
    STATUS_RESPONSE,
    PEER_LIST,
    MANUAL_MESSAGE,
    SNAPSHOT_TRIGGER,
    START_SNAPSHOT,
    LOCAL_SNAPSHOT_DONE
}
