package trafficsync.common;

public enum MessageType {
    REGISTER,
    REGISTER_ACK,
    TRAFFIC_UPDATE,
    MARKER,
    SNAPSHOT_RESPONSE,
    STATUS_RESPONSE,
    PEER_LIST,
    MANUAL_MESSAGE,
    SNAPSHOT_TRIGGER,
    START_SNAPSHOT,
    LOCAL_SNAPSHOT_DONE
}
